# Generated by Django 3.2.9 on 2021-11-14 08:17

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_alter_author_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobiePrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
    ]
