# Generated by Django 3.2.9 on 2021-11-14 08:18

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_mobieprie'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobiePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', tinymce.models.HTMLField()),
            ],
        ),
        migrations.DeleteModel(
            name='MobiePrie',
        ),
    ]
