# Generated by Django 3.2.9 on 2021-11-14 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20211114_1403'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MobiePrice',
            new_name='MobilePrice',
        ),
    ]
